name: 'Spell Check'

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  spell-check:
    name: Check for spelling errors
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run spell checker
        run: npm run lint:spell
