name: TypeScript Type Check

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  typecheck:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x] # Use recent Node versions

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install root dependencies
        run: npm ci

      # No need to run `npm run build` explicitly here because
      # the `test:ts` script includes it.

      - name: Run TypeScript Type Check
        run: npm run test:ts
